### ISSUE TITLE
デプロイをする

### ISSUE THREAD

**Issue by Mackyson** [Mackyson/Haique#18]
ゆかりおんさん、ガンバレ！😀

**Comment by Yukarion** [comment]
ACIでdocker-composeをもとにデプロイしようとしたところ，要求CPU数が多すぎる(上限4のところ5つ使用)らしく，使用数の上限をつけたくてservice.deploy.resource.limitsで制限をつけたのに制限が効かない．
この原因は，そもそもdocker-composeでdeployは対応してないぽい．-compaibilityオプションを利用するとできるらしいけど本番環境では使わない方がよいらしい(https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-mode) ＆使ってもどの部分がdocker-composeが原因で怒られてそうなどうしようもない感じの文字コードのエラーが出る．

＼(^o^)／

エラーコード
CPU数多すぎって怒られたときのヤツ
`$ docker compose up

containerinstance.ContainerGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ServiceUnavailable" Message="The requested resource is not available in the location 'japanwest' at this moment. Please retry with a different resource request or in another location. Resource requested: '5' CPU '8.1' GB memory 'Linux' OS"`

制限する記載をしたのに出るヤツ
`$ docker-compose up --build -d

WARNING: Some services (api-server, bff, redis, web-server) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use docker stack deploy to deploy to a swarm.`

オプションつけたら怒られたときのヤツ
`$ docker-compose –compatibility push

Traceback (most recent call last):

  File "bin/docker-compose", line 6, in <module>
  
  File "compose/cli/main.py", line 67, in main
  
  File "compose/cli/main.py", line 99, in dispatch
  
  File "compose/cli/docopt_command.py", line 31, in parse
  
  File "compose/cli/docopt_command.py", line 42, in get_handler
  
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

Failed to execute script docker-compose`

docker version 20.10.11
docker-compose version 1.16.1
